### PR TITLE
Updated build.

### PR DESCRIPTION
**Pull request by kylevedder**
- Added Debug and Release modes:
    - Debug uses `clang++`, as it provides faster build times and far better error messages.
    - Release uses `g++`, as historically `g++` has produced faster binaries (though this is worth looking into further, LLVM has gotten very good).
 - Fixed `clang-tidy` target.
    - Fixed target's invocation to use the generic version, `run-clang-tidy`.
    - Added command to automatically generate the compile database for `clang-tidy`'s use.
 - Replaced the file list with extension based globs to make future file additions easier to manage.
 - Updated README.md with instructions on how to build both modes.

### CODE REVIEW

**Comment by whoenig** [comment]
I understand the reasoning for the new debug/release targets, but I think this has many disadvantages:

1. It breaks cross-platform compatibility. (This wont work as intended for mac/windows). I know there is now CI for those targets, but I hope to add that at some point.
2. It forces other devs to agree with your compiler preferences. The whole idea of cmake is, that you can use it with any compiler, and cmake will figure out the right flags for you.

I personally don't like cmake's globs because it can cause issues with the dependencies, see https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil, for example.

**Comment by kylevedder** [comment]
Your comments all make sense. I had no idea about the glob issues; to be honest, I don't know very much about CMake and I usually [wrap all interaction with it in a Makefile](https://github.com/umass-amrl/minutebots-public/blob/master/Makefile).

In that case I think the only things of value to salvage out of this commit are:

1. Adding `-g` to the list of flags as it makes cores readable
2. Invoking the more general `run-clang-tidy` in the `clang-tidy` target
3. Dumping the compile database so the `clang-tidy` target works out of the box

Let me know if this is reasonable and I will update my PR accordingly in the next day or so.

**Comment by whoenig** [comment]
I agree with 2. + 3.. For 1. the traditional CMAKE way is to configure the build in debug using `cmake -DCMAKE_BUILD_TYPE=Debug ..`, which could be added to the readme if it's not there yet. Cmake will then add `-g` (or another flag if your system uses a different compiler).

**Comment by kylevedder** [comment]
OK, thanks for the info about how CMAKE works, I really need to learn how to use it properly. I have made the changes discussed in 2. and 3.

**Comment by whoenig** [comment]
Thanks!

**Pull request merged**
